---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---


## 網站資料爬取
```{r}
#install.packages("rvest")
library(rvest)
pttNBA <- c("https://www.ptt.cc/bbs/NBA/index4614.html","https://www.ptt.cc/bbs/NBA/index4615.html", "https://www.ptt.cc/bbs/NBA/index4616.html", "https://www.ptt.cc/bbs/NBA/index4617.html", "https://www.ptt.cc/bbs/NBA/index4618.html", "https://www.ptt.cc/bbs/NBA/index4619.html", "https://www.ptt.cc/bbs/NBA/index4620.html")
for(n in 1:7) {
    pttNBAContent <- read_html(pttNBA[n])
post_title <- pttNBAContent %>%
    html_nodes(".title") %>% html_text()
post_pushNum <- pttNBAContent %>%
    html_nodes(".nrec") %>% html_text()
post_author <- pttNBAContent %>%
    html_nodes(".author") %>% html_text()
if(n == 1) {
    pttNBA_postsAll <- data.frame(Title = post_title, PushNum = post_pushNum, Author = post_author)
} else {
    pttNBA_posts <- data.frame(Title = post_title, PushNum = post_pushNum, Author = post_author)  
    pttNBA_postsAll <- rbind(pttNBA_postsAll, pttNBA_posts)
  }
}
```

## 爬蟲結果呈現
```{r}
knitr::kable(
    pttNBA_postsAll[c("Title", "PushNum", "Author")])
```

## 解釋爬蟲結果 
- 共爬出幾篇文章標題？
```{r}
str(pttNBA_postsAll)
```

A: 總共有140篇文章。


- 哪個作者文章數最多？
```{r}
authorCount <- data.frame(Author = unique(pttNBA_postsAll$Author), Count = 0)
for(i in 1:nrow(authorCount)) {
    for(j in 1:nrow(pttNBA_postsAll)) {
        if(authorCount$Author[i] == pttNBA_postsAll$Author[j]){
            authorCount$Count[i] = authorCount$Count[i] + 1
        }
    }
}
authorCount <- authorCount[order(-authorCount$Count, authorCount$Author),]
knitr::kable(
    authorCount[1:5, c("Author", "Count")])
```

A: 發文數排名前五名如上，Rambo的文章最多。

- 其他爬蟲結果解釋
    - 在NBA版有個文章分類是Live，應該是在有直撥比賽的時候的討論串。可以發現一些人氣較高的球隊的比賽關注人數及討論熱度都比較高，例如：勇士、騎士、火箭隊等，堆文數都到達「爆」的等級。其他像是一些八卦的討論串討論熱度也很高，由此可見台灣人有多愛八卦了。反而像是戰術分析之類的討論串討問熱度就不如前兩種高，所以我們可以推論出：喜歡觀賞NBA比賽的人不見得會（喜歡）打籃球。